
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###

GET http://localhost:3000/states/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjU4MzA3NzEwfQ.1Kp8fVdRmPBtztPxZwbfYpE--HALN6IPYeTzIYxr-Sk
###

GET http://localhost:3000/states/8/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjU4MzA3NzEwfQ.1Kp8fVdRmPBtztPxZwbfYpE--HALN6IPYeTzIYxr-Sk
###

POST http://localhost:3000/districts/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjU4MzA3NzEwfQ.1Kp8fVdRmPBtztPxZwbfYpE--HALN6IPYeTzIYxr-Sk
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###

GET http://localhost:3000/districts/10/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjU4MzA3NzEwfQ.1Kp8fVdRmPBtztPxZwbfYpE--HALN6IPYeTzIYxr-Sk
###

DELETE http://localhost:3000/districts/12/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjU4MzA3NzEwfQ.1Kp8fVdRmPBtztPxZwbfYpE--HALN6IPYeTzIYxr-Sk
###

PUT http://localhost:3000/districts/:15/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjU4MzA3NzEwfQ.1Kp8fVdRmPBtztPxZwbfYpE--HALN6IPYeTzIYxr-Sk
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###

GET http://localhost:3000/states/5/stats/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjU4MzA3NzEwfQ.1Kp8fVdRmPBtztPxZwbfYpE--HALN6IPYeTzIYxr-Sk